# Writing a detailed methods section {#chapter2}

For statistical analyses to be reproducible without sharing the statistical code, the data must be available and the description of all data cleaning, management, and analysis decisions must include enough detail to be repeated.[@Harris2018] This may sound straightforward until you start thinking of everything that goes into the data analysis process from choosing which software to use to deciding whether to report p-values as an inequality or not.

## Software details

Once the data are obtained, the first decision an analyst will likely make is choosing which software to use to clean, manage, and analyze the data. There are many options for analyzing quantitative data ranging from the Microsoft Excel software that comes standard with many computers, to proprietary options like SAS software and SPSS Statistics for Windows, to open source options like R and Python.

Different software options have different features and capabilities, some of which can make reproducibility more difficult to attain. Excel, for example, relies mostly on a point-and-click and menu-driven interface where the user chooses options and makes edits without writing any code or keeping a list of all the steps taken. SAS and R, on the other hand, rely primarily on the user writing code to perform most tasks, which serves as a running list of what the user has done with the data. 

### Which software package(s)

Although it may seem unnecessary to provide the software package and version (a regression analysis is a regression analysis, right?), this can actually be very important for reproducibility. Take, for example, a chi-squared test of independence. 

```{r}
library(package = "palmerpenguins")
oneway.test(formula = flipper_length_mm ~ year, 
       data = penguins)
summary(aov(formula = flipper_length_mm ~ as.factor(year), 
       data = penguins))
```


### Which version(s)

Not only do different software packages often do things in slightly different (or very different) ways, but software gets updated over time, which can change the algorithms underlying the procedures being used.

### 

### Data cleaning and management

### Units of analysis

### Sample sizes

### Variable types

### Variable recoding details

### Missing data coding

## Analysis

### Statistical approaches

### Specific variables in each statistical model

### Missing data handling

### Analytic sample size

## Results

### Test statistics

### Precise p-values

## Methods section examples and exercises
