---
title: "An introduction to reproducible research practices for social scientists"
author: "Jenine K. Harris"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  word_document: 
    reference_docx: "template.docx"
  bookdown::word_document2: 
    reference_docx: "template.docx"
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
editor_options: 
  markdown: 
    wrap: 72
---

# Chapter 1: Science vs. Memes (\#chapter1)

> "I don't know if Franklin actually said this but I like it anyway!" -
> Uncle Nick, Facebook, August 30, 2016

In the months just prior to the 2016 Presidential election, the
political differences between me and some of my family members became
very clear. One place this showed up was on Facebook, where I would use
Fact Checking websites like Snopes to challenge or debunk memes often
showing false quote or facts posted by my Uncle Nick. This frequent
interaction culminated in Nick adding a disclaimer (quoted above) to a
meme he shared on Facebook. The meme included a picture of Benjamin
Franklin with the quote, "Make yourself sheep and the wolves will eat
you" attributed to Franklin and a logo for The Patriot Post. This quote
is accurately attributed to Benjamin Franklin, but this was not
important to Nick. The important part was that he liked the quote and
wanted to share it with others. Nick is not the only one using social
media to share information, nor is social media the only place where
information is shared.

In everyday life we are surrounded by sources of information. We have
online and offline conversations with friends and colleagues and Uncle
Nick, read comments from strangers on the internet, watch news online
and on television, and read magazines and books and government reports.
Maybe we even look up and read (or skim) the occasional scientific
article. Not all of these sources of information are the same. Sources
of information vary widely in quality.

There are many different things that can impact the quality of
information. Information quality can be impacted by the author of the
information through author bias, author motive, and author expertise.

Author bias

Author motive

Author expertise

## The scientific quality crisis 

Science is arguably better than common sense at helping us understand the world, yet it is still far from perfect. In recent decades, the academic culture of publish or perish has collided with technological advances in publishing resulting in an exponential growth in published research. Whether by correlation or causation (or both), challenges currently facing science coincide with this rapid growth, including increasing rates of retraction, a lack of research reproducibility, and the proliferation of predatory journals. So, while science is moving quickly on quantity, increases in quantity are coming at the expense of research quality. Low quality research has high human and financial costs not only for those participating in the research, but also for society.

ii. Reasons for poor quality 
1. Fraud (26%) 
2. Error (74%)  

One way to improve scientific quality is to use reproducible research practices. Research is reproducible when the data and software are accessible, and the data management and analysis steps are clear and complete. While some reproducible research practices have become more common, there is a notable lack of widespread adoption of many reproducible research practices. When asked what would facilitate their own use of reproducible research practices, the top answer from public health researchers was training on reproducible research practices.

This book aims to fill this need by providing undergraduate and graduate students in the social sciences with an introduction to reproducible research practices. To my knowledge, no book exists with the purpose of providing guidance on developing reproducible research practices in the social sciences. The text is designed as a supplemental text for research methods courses and for introductory and intermediate statistics courses across social science disciplines. 



## How reproducible research can help 

i. Increases research quality, promotes collaboration, reduces research waste 
ii. Distinction from repeatable and replicable iii. 

## Qualities that make research reproducible 

1. Access to data and software 

2. Well-organized statistical code or sufficiently detailed methods

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
